freeipa/freeipa-perftest

README.md
create-test-data.py
set-password.py

create-test-data.py comes from the freeipa-tools repo. It is
designed to create complex test data including nested groups,
hbac and sudo rules. It provides way more than we need here but
we may be able to build on it.
As such, this overrides some of its methods to generate a
number of users per host with a given username format.
Whether we can mangle this into creating the other entry types in
the future is TBD but I think it is possible.
The password is 'password'.
Users are created in the form: user#client#.<domain>
Signed-off-by: Rob Crittenden <rcritten@redhat.com>

Add tools to create test users with unexpired passwords

---

ipaperftest.py

Add `ipareplicas` group to the list of hosts to collect logs from in the ansible playbook.

Fetch logs from replicas

---

create-test-data.py
set-password.py
setup.py
src/ipaperftest/core/constants.py
src/ipaperftest/core/main.py
src/ipaperftest/plugins/authenticationtest.py
src/pamtest.c

Add test to simulate client authentications using a pam tool
The purpose of the test is to determine the maximum number of
authentications an IPA server is capable of. The general rule
of thumb has been 2-3000 clients per server. The intention of
this test is to back that up with numbers.
This is an IPA-centric test so only using IPA users and only
authenticating via SSSD using the PAM login service. A single
authentication for each user is done.
The basic idea is:
- Deploy some client machines, trying to gate their installation
so that all are successful
- Create a bunch of users in IPA for each specific host in the form
of user000client000.ipa.test
- Set Kerberos and LDAP passwords for every user to 'password'
- Run the pamtest tool with a number of threads and collect the
result
- Pull …

Add test to simulate client authentications using a pam tool

---

freeipa-perftest.spec

This is needed to build against Fedora 35+ chroots in copr.

freeipa-perftest.spec: Add python3-setuptools to BuildRequires

---

src/ipaperftest/plugins/apitest.py

APITest was generating "amount" clients. However in this test we want
one client per 50 commands. Also increase available memory to 1GB since
in this test we need more memory for handling all the commands and we
don't need to deploy as many clients as in other tests such as
EnrollmentTest.

APITest: update client generation settings

---

src/ipaperftest/core/constants.py
src/ipaperftest/core/main.py
src/ipaperftest/core/output.py
src/ipaperftest/core/plugin.py
src/ipaperftest/plugins/apitest.py
src/ipaperftest/plugins/authenticationtest.py
src/ipaperftest/plugins/enrollmenttest.py
src/ipaperftest/plugins/registry.py

This allows to differentiate between successes, warnings and errors
during test execution, as well as outputting the results as either
human-readable or JSON format. Instead of directly printing results,
tests will yield a Result instance with the required information.
Based on implementation from freeipa-healthcheck: https://github.com/freeipa/freeipa-healthcheck

Add Result and Output classes for better formating of results

---

README.md

An additional # was missing for both AuthenticationTest and APITest
sections, resulting in a malformed README.

README: fix heading formatting

---

src/ipaperftest/core/plugin.py

This resolved some VM startup failures seen when running the
authentication tests.
Signed-off-by: Rob Crittenden <rcritten@redhat.com>

Restart libvirtd between executions

---

README.md
src/ipaperftest/core/constants.py
src/ipaperftest/core/main.py
src/ipaperftest/core/plugin.py
src/ipaperftest/plugins/apitest.py
src/ipaperftest/plugins/authenticationtest.py
src/ipaperftest/plugins/enrollmenttest.py
src/pamtest.c

Add Active Directory support to AuthenticationTest. This will create a
Windows Server host and deploy Active Directory server on it. After
that, test users are created into AD and trust is established with the
IPA server.
The pamtest tool is also updated to support launching threads for
authenticating Active Directory users.

AuthenticationTest: Add Active Directory support

---

src/ipaperftest/plugins/authenticationtest.py

This Result is incorrectly returned, since it's purpose is to detect
when total_threads == 0, but that would cause a ZeroDivisionError that
is already handled by the generic exception catching in
7b9d3e756d11691d8d2078e17dc09ee177725355. Because of this, the Result is
only returned when in reality there are no errors.

Remove unneeded Result during AuthenticationTest post-process

---

src/ipaperftest/plugins/apitest.py

Move the output collected from commands into the sync directory.

APITest: collect command logs from clients

---

src/ipaperftest/core/constants.py
src/ipaperftest/plugins/apitest.py

Since commands will be scheduled and launched from the clients, we
should use the client localtime for scheduling instead of the server's,
that way we can avoid issues caused by differences in time configuration.

Use client localtime for APITest instead of server time

---

.gitignore
README.md
requirements.txt
src/ipaperftest/core/constants.py
src/ipaperftest/core/main.py
src/ipaperftest/core/plugin.py
src/ipaperftest/plugins/apitest.py
src/ipaperftest/plugins/authenticationtest.py
src/ipaperftest/plugins/enrollmenttest.py
src/ipaperftest/providers/idmci.py
src/ipaperftest/providers/provider.py
src/ipaperftest/providers/vagrant.py

Use IdM-CI to run the performance tests using Red Hat's internal
infrastructure instead of using Vagrant as a provisioner. This allows us
to run the tests without the need of having all the VMs on the same
host, which could cause limitations on the libvirt side in some
situations.

Use IdM-CI for provisioning

---

src/ipaperftest/plugins/apitest.py
src/ipaperftest/providers/vagrant.py

Measure how much time it takes to run all scheduled commands. We add a
sleep right before we start checking the command statuses so that the
wait time is not included in the measurement.

APITest: measure test execution time

---

README.md
src/ipaperftest/core/main.py
src/ipaperftest/plugins/apitest.py

When the --sequential flag is used, APITest will run in sequential mode.
In this mode, only one client is deployed, and commands are executed
sequentially from it.

APITest: add option to run commands sequentially

---

src/ipaperftest/core/constants.py
src/ipaperftest/plugins/apitest.py

With high amount of commands (2000+) simply joining the list of commands
with && would fail with "/bin/sh: Argument list too long". Write
commands to script and run it instead.

APITest: write commands to script when running in sequential mode

---

src/ipaperftest/core/constants.py
src/ipaperftest/core/main.py
src/ipaperftest/plugins/authenticationtest.py
src/pamtest.c

SSSD currently has a mutex when calling pam in threaded
more so it is effectively serialized. Add an option to call
PAM using fork() instead to run the authentications
simultaneously.
There is a lock in libsemanage which can cause failures
so disable the SELinux provicer as a workaround for that.
Signed-off-by: Rob Crittenden <rcritten@redhat.com>

Add option to disable SELinux and enable forking in authtest

---

freeipa-perftest.spec
src/pamtest.c

pamtest was unable to perform AD authentications when using the -f option.

AuthenticationTest: allow running forks with AD users

---

src/ipaperftest/core/main.py
src/ipaperftest/plugins/authenticationtest.py

By using minutes instead of seconds, the authentications are spreaded more evenly, since it guarantees there will be at least 1 minute of difference between authentications that aren't simultaneous.

AuthenticationTest: use minutes for spread instead of seconds

---

src/ipaperftest/core/constants.py

We need to enable repositories in RHEL in order to install needed packages such as `sysstat` or `ipa-server`.

Configure default repos in RHEL systems

---

src/ipaperftest/plugins/apitest.py
src/ipaperftest/plugins/authenticationtest.py
src/ipaperftest/plugins/enrollmenttest.py

Return the number of successes for each test as part of the result JSON, so it can be easily parsed by a test runner.

Return number of successes in test result

---

src/ipaperftest/providers/idmci.py
src/ipaperftest/providers/vagrant.py

Default base image for IdM-CI and Vagrant providers was set to Fedora 34, which is no longer supported and got its chroots in COPR removed. Update to the latest stable release, Fedora 38.

Update base images to Fedora 38

---

src/ipaperftest/plugins/groupsizetest.py

Using --no-member causes the membership to not be calculated in IPA which makes the data return much faster. This is not enabled in the UI or CLI by default. This change was left in accidentally. It does improve the times a bit.
A syntax error in setting the GroupSizeTest archive name resulted in no failure but there was no resulting tarball for the execution.

Remove --no-member, fix up GroupSizeTest tarballs

---

src/ipaperftest/core/constants.py

This is needed in the AuthenticationTest. With SELinux enabled there is a lock in SSSD that prevents simultaneous logins.

Restart SSSD after disabling the SELinux provider

---

README.md
src/ipaperftest/core/main.py
src/ipaperftest/core/plugin.py

Include the test result output to the log archive, apart for printing it to stdout or the selected output file.

Add test result to log archive

---

gencerts.sh

This will be used for load, performance and migration testing.
It works by issuing a cert for a new service over and over again. The certificate itself is dropped from the filesystem and the service entry because there should be no need to have potentially thousands of unique certificates lying around.

Add script to generate certificates

---

src/ipaperftest/core/constants.py
src/ipaperftest/core/plugin.py

Apart from adding the SSH private key to the SSH arguments, we need to set the `private_key_file` option in ansible.cfg.

ansible config: set private key explicitly

---

README.md
create-test-data.py
setup.py
src/ipaperftest/core/constants.py
src/ipaperftest/core/main.py
src/ipaperftest/plugins/certissuetest.py

This test creates a number of clients and enrolls them. Then it creates a number of services for each client and runs ipa-getcert on all of them.
This is to try to identify the number of simultaneous certificate requests that the server can manage. There is no real effort to fully synchronize the requests since in reality they all won't fire at the same time either.
There is one additional tuning option, the WSGI processes, which is not exposed on the command-line. This can be tuned directly in the constants file.

Add Certificate issuance test
